#!/bin/bash

###############
#  Arch Blue  #
###############
#
#bg_normal='#333333'
#fg_normal='#efefef'
#bg_focus='#00aad4'
#fg_focus='#efefef'
#bg_urgent='#ff4070'
#fg_urgent='#efefef'
#
#fg_grey='#ababab'
#fg_red='#ff6699'
#fg_green='#d5f85f'
#fg_yellow='#ffa466'
#fg_blue='#00aad4'

###############
#  Section 9  #
###############
#
#bg_normal='#333333'
#fg_normal='#efefef'
#bg_focus='#714BA7'
#fg_focus='#efefef'
#bg_urgent='#ff4070'
#fg_urgent='#efefef'
#
#fg_grey='#ababab'
#fg_red='#ff6699'
#fg_green='#d5f85f'
#fg_yellow='#ffa466'
#fg_blue='#00aad4'

###############
#  Lain Blind #
###############
#
#bg_normal='#262626'
#fg_normal='#c1b48e'
#bg_focus='#d0758b'
#fg_focus='#efefef'
#bg_urgent='#ff4070'
#fg_urgent='#efefef'
#
#fg_grey='#808080'
#fg_red='#d0758b'
#fg_green='#d0758b'
#fg_yellow='#d0758b'
#fg_blue='#d0758b'

###########
#  Aigis  #
###########

bg_normal='#262626'
fg_normal='#c1b48e'
bg_focus='#d0758b'
fg_focus='#efefef'
bg_urgent='#ff4070'
fg_urgent='#efefef'

fg_grey='#566a72'
fg_red='#ba5654'
fg_green='#badbb4'
fg_yellow='#b9c780'
fg_blue='#99cff3'

bheight=18

#dfont='-*-stlarch-medium-r-*-*-10-*-*-*-*-*-*-*,-*-fixed-medium-*-*-*-12-*-*-*-*-*-*-*'
bfont1='-*-stlarch-medium-r-*-*-10-*-*-*-*-*-*-*'
bfont2='-*-fixed-medium-*-*-*-12-*-*-*-*-*-*-*'
efont='-*-tamsyn-medium-*-*-*-14-*-*-*-*-*-*-*'


