##########
#  MAIN  #
##########

directory: ~/music
library: ~/.config/beets/library.blb
        
###############
#  IMPORTING  #
###############
        
import:
        copy: yes
        group_albums: yes
        timid: yes
        write: yes

match:
        ignored: missing_tracks unmatched_tracks

#############
#  PLUGINS  #
#############

plugins: acousticbrainz absubmit convert chroma discogs fetchart fuzzy info mpdupdate scrub edit zero

convert:
        auto: no
        copy_album_art: no
        embed: no
        never_convert_lossy_files: no
        format: opus

chroma:
        auto: yes
        
fetchart:
        auto: yes

acousticbrainz:
        auto: yes

absubmit:
        auto: yes

zero:
        auto: yes
        fields: comments
                
fuzzy:
        prefix: '@'
        threshold: 0.8
                
mpd:
        host: localhost
        port: 6600
