#!/bin/sh

# The key combo argument has the following form: "[C-][M-][S-]KEY",
# where C/M/S indicate Ctrl/Meta(Alt)/Shift modifier states and KEY is the X
# keysym as listed in /usr/include/X11/keysymdef.h without the "XK_" prefix.

case "$1" in
"C-c")
        echo -n "$2" | xclip -selection clipboard ;;
"C-d")
        rm "$2" ;;
"C-g")
        gimp "$2" & ;;
esac
