#!/usr/bin/env zsh
# power off after mpd stops playing

mpc play > /dev/null
while true; do
    mpc idle player > /dev/null || return 1
    if [[ -z "$(mpc status | grep playing)" ]]; then
        poweroff
    fi
done
